networks:
  external_access:
    external: true

services:
  password-generator:
    build: .
    container_name: password-generator
    restart: always
    networks:
      - external_access
    volumes:
      - counter-data:/app/data
    ports:
      - "52931:5000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.lykilord.rule=Host(`lykilord.runr.is`)
      - traefik.http.services.lykilord.loadbalancer.server.port=5000
      - traefik.http.routers.lykilord-https.tls=true
      - traefik.http.routers.lykilord-https.tls.certresolver=cloudflare
      - traefik.http.routers.lykilord-https.rule=Host(`lykilord.runr.is`)

volumes:
  counter-data:
